### ISSUE TITLE
How to run vina-gpu on windows 10

### ISSUE THREAD

**Issue by bioleo** [DeltaGroupNJUPT/Vina-GPU#1]
How to run vina-gpu on windows 10. I tried to use this software, and it felt unusable. The error appeared Platform: NVIDIA CUDACould not open file: C:\Users\ADMINI~1\AppData\Local\Temp\dep-c25713.d. How did this error happen? ? How should I configure my computer to use vina-gpu on windows 10? Can you describe in detail how to set these steps? E.g:
add ./lib ./OpenCL/inc $(YOUR_BOOST_LIBRARY_PATH)/boost $(YOUR_CUDA_TOOLKIT_LIBRARY_PATH)/CUDA/v11.5/include in the include directories;

add $(YOUR_BOOST_LIBRARY_PATH)/stage/lib $(YOUR_CUDA_TOOLKIT_PATH)/CUDA/lib/Win32in the addtional library;

add OpenCL.lib in the additional dependencies。

**Comment by Glinttsd** [comment]
Hi, we are sorry for the inconvenience, Vina-GPU is still under developing and we are glad to hear any feedback. We recently updated our readme, please check it out. For Windows users, on the first run of Vina-GPU, we recommand you to run `Vina-GPU-K.exe` directly with the command `./Vina-GPU-K.exe --config ./input_file_example/2bm2_config.txt` to run Vina-GPU on our example complex. Once succeed, you should see the docking result file and `Kernel2_Opt.bin` file. After that, you can run `Vina-GPU.exe` with a similar command to run Vina-GPU without compiling the kernel file (thus to save runtime). If you want to build Vina-GPU from source code, we recommand you to use Visual Studio 2019. If you are not familiar with Visual Studio 2019, please check this [tutorial](https://visualstudio.microsoft.com/zh-hans/vs/getting-started/). Best regards!

**Comment by bioleo** [comment]
thank you very much! This software is running very well！
