### ISSUE TITLE
Err-30:CL_INVALID_VALUE

### ISSUE THREAD

**Issue by naeemmrz** [DeltaGroupNJUPT/Vina-GPU#15]
I've recently compiled Vina-GPU however when I run the command:
`./Vina-GPU --config ./input_file_example/2bm2_config.txt`

I get the error:
`Reading input ... done.
Setting up the scoring function ... done.
Analyzing the binding site ... done.
Using random seed: -108247774

Platform: NVIDIA CUDA
Device: Tesla T4

Search depth is set to 6
Err-30:CL_INVALID_VALUE`

My gcc and g++ are both 10.3.0 and cuda is 11.1 (installed via conda)

Background to how I've compiled it:

1. I've installed the following packages
`conda install -c conda-forge rdkit
conda install -c hcc adfr-suite`

2. Downloaded and decompressed Boost and Vina-GPU and ran `ulimit -s 8192`

3. Changed the Makefile content as:
`BOOST_LIB_PATH=/content/boost_1_77_0
OPENCL_LIB_PATH=/usr/local/cuda` 
and then 
`cd Vina-GPU-main/ && make clean && make`
I've got several warning and deprecation messages but no errors and "Vina-GPU" was generated.

Any ideas about what might be causing the problem?

**Comment by Glinttsd** [comment]
You should:
1. `make clean` & `make source`
2. run `Vina-GPU` binary file, so that a `Kernel2_Opt.bin` file can be generated
3. if step 2 works well, `make clean` & `make`, then you can run `Vina-GPU` (new version) smoothly, and make sure dont change `Kernel2_Opt.bin`

**Comment by naeemmrz** [comment]
I did as you have mentioned @Glinttsd but the error still persists.
1. I decompressed the Vina-GPU, and cd into it.
2. make clean && make source, it did generate a Kernel2_opt.bin but at this step when I raw
`
./Vina-GPU --config ./input_file_example/2bm2_config.txt
` 
I got the following error
`
Error: Failed to build program executable!
log:Error parsing value of -cl-std flag!
Search depth is set to 6
Err-30:CL_INVALID_VALUE
`
I did step 2 again by just running ./Vina-GPU to generate Kernel2_opt.bin and then ran `make clean && make` but still got the same error.

**Comment by Glinttsd** [comment]
Well, this time, the error is due to a low version GPU driver, which does not support OpenCL 3.0. You can either 1. upgrade your GPU driver to the newest verison by which OpenCL 3.0 is supported and then `make source`  or 2.  `git pull` and replace the default `-DOPENCL_3_0` with `-DOPENCL_1_2` in the `Makefile` to compile the kernels with OpenCL 1.2

**Comment by naeemmrz** [comment]
@Glinttsd 
Thanks, changing to -DOPENCL_1_2 fixed it.
This might be off-topic but could you provide any suggestion on how I could update to OpenCL 3.0? I'm running on a Ubuntu server and don't have root-priveledges. I wasn't able to update it via pip and conda.

**Comment by Glinttsd** [comment]
I've nerver installed CUDA via `conda` or `pip`. The way I usually do is to download the newest version of GPU driver on the [NVIDIA website](https://www.nvidia.com/download/index.aspx) and install it locally. Maybe you could try that way.
