### ISSUE TITLE
Quick Clarifying Question about GPUs

### ISSUE THREAD

**Issue by papaSneetch** [DeltaGroupNJUPT/Vina-GPU#16]
So while testing the program we noticed that it wasn't using all of the gpus on our system. It looks like Vina-GPU is successful detecting all the gpus based on this output.

```
Using random seed: 1833385468

Platform: NVIDIA CUDA
Device: Tesla V100S-PCIE-32GB

Device: Tesla V100S-PCIE-32GB

Device: Tesla V100S-PCIE-32GB

Device: Tesla V100S-PCIE-32GB

Search depth is set to 6
```
However, Vina-GPU is using only one gpu based on some diagnostics tools that I used. It's probably something to do with how things are configured in our system that I'll need to find, however I just wanted to confirm real quick if Vina-GPU is designed to fully utilize multiple gpus in a system or just a singular one. I'll assume its designed to use multiple, however if it isn't designed with multiple gpus in mind, that would be nice to know so I don't go on a wild goose chase.

**Comment by Glinttsd** [comment]
Hi, currently Vina-GPU is designed to use **single** GPU card.

**Comment by papaSneetch** [comment]
Thanks for letting me know. I guess this would be a feature request then.
