### ISSUE TITLE
Choose which GPU to use in a multi-GPU system

### ISSUE THREAD

**Issue by SamuelOjeda** [DeltaGroupNJUPT/Vina-GPU#23]
Since vina-GPU is designed to use a Single GPU at a time, would it be possible to set vina-GPU command or config file to use a specific GPU on the system? 
My goal is to split my ligand library into 4 and then run each quarter using one of the system's 4GPUs at a time.

**Comment by Glinttsd** [comment]
Hi, we can not provide multi-GPU running in the current version but we will. 

A possible workaround is to alter the GPU device which is fixed to be `0` (aka the first device) at `OpenCL/src/wrapcl.cpp: line 338` for each Vina-GPU run and run multiple Vina-GPU at the same time.

**Comment by Glinttsd** [comment]
A simple solution is to set enviroment variable `CUDA_VISIBLE_DEVICES` to the device you want to use, e.g. `export CUDA_VISIBLE_DEVICES=0` and then run `Vina-GPU`
