### ISSUE TITLE
error while loading shared libraries: libboost_program_options.so.1.79.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by purnawanpp** [DeltaGroupNJUPT/Vina-GPU#24]
Hi I have problem, how to solved this:
./Vina-GPU --config ./input_file_example/2bm2_config.txt
./Vina-GPU: error while loading shared libraries: libboost_program_options.so.1.79.0: cannot open shared object file: No such file or directory

**Comment by Glinttsd** [comment]
Hi, this is a common shared library path issue. This [link ](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s)could be helpful for you. The boost library is normally installed in `/usr/local/lib`.
