### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by JerryJohnsonLee** [DeltaGroupNJUPT/Vina-GPU#26]
Hi, I am not able to compile the code on Linux system. When I do `make source`, I get the following error messages:

> /usr/bin/ld: cannot find -lboost_program_options
> /usr/bin/ld: cannot find -lboost_system
> /usr/bin/ld: cannot find -lboost_filesystem
> collect2: error: ld returned 1 exit status
> make: *** [source] Error 1

Because I do not have sudo privileges, I downloaded boost 1.80 and stored it under the root folder of the repository. I have also installed CUDA toolkit (11.7) under upper folder relative to the repository. I have changed Makefile accordingly, so its first several lines read:

> BOOST_LIB_PATH=boost_1_80_0
> OPENCL_LIB_PATH=../cuda_11_7
> OPENCL_VERSION=-DOPENCL_3_0
> GPU_PLATFORM=-DNVIDIA_PLATFORM

Using the same settings I actually can compile the code in an Ubuntu 20.04.2LTS machine which I have root privileges. But I cannot compile the code on the cluster that has Red Hat 4.8.5-44. I am using GCC version 10.2.

Any help is greatly appreciated!

**Comment by Glinttsd** [comment]
Hi, `ld` issue is a common problem for compiling any program. I think your path settings in the `Makefile` are correct. You can check this [link](https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary), which provides a way to dig into the `ld` problem by adding  `--verbose` option. You can maybe create a soft link to your own, for example,  `boost_system.so` file. Hope it helps.

**Comment by JerryJohnsonLee** [comment]
Thanks for the info! However as I understand it, the command executed during `make` is actually:
> gcc -o Vina-GPU -Iboost_1_80_0 -Iboost_1_80_0/boost  -I./lib -I./OpenCL/inc  -I../cuda_11_7/include ./main/main.cpp -O3 ./lib/*.cpp ./OpenCL/src/wrapcl.cpp boost_1_80_0/libs/thread/src/pthread/thread.cpp boost_1_80_0/libs/thread/src/pthread/once.cpp  -Lboost_1_80_0/stage/lib -L../cuda_11_7/lib64 -lboost_program_options -lboost_system -lboost_filesystem -lOpenCL -lstdc++ -lm -lpthread -DOPENCL_3_0 -DNVIDIA_PLATFORM 

I am not exactly sure in which step is `ld` executed and how I can add options to it. 

Also, in my success compilation of the code I did not find the `boost_system.so` file. Is it supposed to be compiled from `make` of Vina-GPU? Otherwise where should I find this file?

**Comment by Glinttsd** [comment]
Hi,

First, the boost library is install needed. Make sure you have installed it. To do that, you can follow the [boost installation guide](https://www.boost.org/doc/libs/1_61_0/more/getting_started/unix-variants.html#easy-build-and-install) here.

Second, `ld` is accutally included in the compilation process using `gcc`. Among the command you posted `gcc -o Vina-GPU ...` you can find `-lboost_program_options -lboost_system -lboost_filesystem`, which are related to `ld`. It will search for available binary files like `boost_system.so` by `ldconfig`. The searching paths are usually defined in `/etc/ld.so.conf.d/`. I think binaries like `boost_system.so` are not properly found, causing the `/usr/bin/ld: cannot find ...` errors. You should check your paths accordingly.

**Comment by JerryJohnsonLee** [comment]
Okay. After properly installing boost library the problem has been solved. Thank you very much!

**Comment by moimaian** [comment]
I noticed that the files that were not found in the compilation are in the /usr/local/boost_1_82_0/lib folder with different names:
-libboost_program_options instead of lboost_program_options
-libboost_system instead of lboost_system
-libboost_filesystem instead of lboost_filesystem
I tried to fix it by editing the makefile file, but it generates the same error.

**Comment by moimaian** [comment]
> Okay. After properly installing boost library the problem has been solved. Thank you very much!

How did you do this installation correctly?

**Comment by moimaian** [comment]
To help other people who will certainly have the same problems, it could be said here in which folders it was extracted and in which folder it was installed. Which options were placed in front of the ./bootstrap and ./b2 install commands. --prefix=(...) --with-libraries=(...) was used. What exactly was put in the PATH environment variables file. Otherwise it becomes a game of trial and error.
