### ISSUE TITLE
Multiple ligands docking

### ISSUE THREAD

**Issue by Draavos** [DeltaGroupNJUPT/Vina-GPU#29]
Hi, when I give Vina-GPU multiple ligands it shows the error "Command line parse error: too many positional options have been specified on the command line".
Is there a way to run with Multiple ligands docking at a time?

**Comment by Glinttsd** [comment]
Hi, multiple ligands docking with a single command line such as `Vina-GPU --ligand=ligand1.pdbqt, ligand2.pdbqt` is not supported in current version of Vina-GPU, we will release a multi-ligand docking verison very soon.

For now, you can run multiple command lines for the purpose of multi-ligand docking. You can write `Vina-GPU --ligand1.pdbqt` and `Vina-GPU --ligand2.pdbqt` into a bash file like `run.sh` and `bash run.sh`.
