### ISSUE TITLE
Build kernels from sourceError: failed to open file

### ISSUE THREAD

**Issue by tavolivos** [DeltaGroupNJUPT/Vina-GPU#3]
Dears 

I am getting the following error: 
__________________________________________________
Platform: NVIDIA CUDA
Build kernels from sourceError: failed to open file
: ./OpenCL/src/kernels/code_head.cppError: failed to open file
: ./OpenCL/src/kernels/mutate_conf.cppError: failed to open file
: ./OpenCL/src/kernels/matrix.cppError: failed to open file
: ./OpenCL/src/kernels/quasi_newton.cppError: failed to open file
Segmentation fault (core dumped)
______________________________________________________

My installation output is this:
_______________________________________________________________
gcc -o Vina-GPU -I/home/zapata/boost_1_77_0 -I/home/zapata/boost_1_77_0/boost  -I./lib -I./OpenCL/inc  -I/usr/local/cuda-11.5/include ./main/main.cpp -O3 ./lib/*.cpp ./OpenCL/src/wrapcl.cpp /home/zapata/boost_1_77_0/libs/thread/src/pthread/thread.cpp /home/zapata/boost_1_77_0/libs/thread/src/pthread/once.cpp  -lboost_program_options -lboost_system -lboost_filesystem -lOpenCL -lstdc++ -lm -lpthread -L/home/zapata/boost_1_77_0/stage/lib -L/usr/local/cuda-11.5/lib64 -DOPENCL_3_0 -DNVIDIA_PLATFORM   -DBUILD_KERNEL_FROM_SOURCE 
In file included from ./lib/monte_carlo.cpp:34:
/home/zapata/boost_1_77_0/boost/progress.hpp:23:108: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> or <boost/timer/progress_display.hpp> instead.
 BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp> or <boost/timer/progress_display.hpp>" )
                                                                                                            ^
In file included from /home/zapata/boost_1_77_0/boost/progress.hpp:25,
                 from ./lib/monte_carlo.cpp:34:
/home/zapata/boost_1_77_0/boost/timer.hpp:21:70: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
 BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
                                                                      ^
./lib/monte_carlo.cpp: In member function ‘void monte_carlo::operator()(model&, output_container&, const precalculate&, const igrid&, const precalculate&, const igrid&, const vec&, const vec&, incrementable*, rng&) const’:
./lib/monte_carlo.cpp:481:66: warning: narrowing conversion of ‘(fl)((const monte_carlo*)this)->monte_carlo::hunt_cap.vec::operator[](0)’ from ‘fl’ {aka ‘double’} to ‘float’ inside { } [-Wnarrowing]
  float hunt_cap_float[3] = {hunt_cap[0], hunt_cap[1], hunt_cap[2]};
                                                                  ^
./lib/monte_carlo.cpp:481:66: warning: narrowing conversion of ‘(fl)((const monte_carlo*)this)->monte_carlo::hunt_cap.vec::operator[](1)’ from ‘fl’ {aka ‘double’} to ‘float’ inside { } [-Wnarrowing]
./lib/monte_carlo.cpp:481:66: warning: narrowing conversion of ‘(fl)((const monte_carlo*)this)->monte_carlo::hunt_cap.vec::operator[](2)’ from ‘fl’ {aka ‘double’} to ‘float’ inside { } [-Wnarrowing]
./lib/monte_carlo.cpp:482:79: warning: narrowing conversion of ‘authentic_v.vec::operator[](0)’ from ‘fl’ {aka ‘double’} to ‘float’ inside { } [-Wnarrowing]
  float authentic_v_float[3] = { authentic_v[0],authentic_v[1], authentic_v[2] };
                                                                               ^
./lib/monte_carlo.cpp:482:79: warning: narrowing conversion of ‘authentic_v.vec::operator[](1)’ from ‘fl’ {aka ‘double’} to ‘float’ inside { } [-Wnarrowing]
./lib/monte_carlo.cpp:482:79: warning: narrowing conversion of ‘authentic_v.vec::operator[](2)’ from ‘fl’ {aka ‘double’} to ‘float’ inside { } [-Wnarrowing]
In file included from ./lib/parallel_progress.h:26,
                 from ./lib/parallel_mc.cpp:26:
/home/zapata/boost_1_77_0/boost/progress.hpp:23:108: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> or <boost/timer/progress_display.hpp> instead.
 BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp> or <boost/timer/progress_display.hpp>" )
                                                                                                            ^
In file included from /home/zapata/boost_1_77_0/boost/progress.hpp:25,
                 from ./lib/parallel_progress.h:26,
                 from ./lib/parallel_mc.cpp:26:
/home/zapata/boost_1_77_0/boost/timer.hpp:21:70: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
 BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
                                                                      ^
In file included from ./lib/parallel_progress.h:26,
                 from ./lib/parallel_progress.cpp:25:
/home/zapata/boost_1_77_0/boost/progress.hpp:23:108: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> or <boost/timer/progress_display.hpp> instead.
 BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp> or <boost/timer/progress_display.hpp>" )
                                                                                                            ^
In file included from /home/zapata/boost_1_77_0/boost/progress.hpp:25,
                 from ./lib/parallel_progress.h:26,
                 from ./lib/parallel_progress.cpp:25:
/home/zapata/boost_1_77_0/boost/timer.hpp:21:70: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
 BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
                                                                      ^
./OpenCL/src/wrapcl.cpp: In function ‘_cl_program* SetupBuildProgramWithBinary(cl_context, _cl_device_id**, const char*)’:
./OpenCL/src/wrapcl.cpp:261:10: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(binary_buffer, sizeof(char), program_size, program_handle);
     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
________________________________________________________________________________________________________

My cuda version is 11.5
Kernel 4.15.0-162-generic
Ubuntu 18.04
DOPENCL_3_0

I would appreciate your help to figure out how to solve this issue.

Thanks in advance!

**Comment by Glinttsd** [comment]
Hi, thanks for your feedback. For the first run of Vina-GPU, you have to build the kernel file from source (that's exactly what you are doing). The errors mean that these source files can not be found or can not be open. This is probably because 1. the executable file `Vina-GPU` is not in the same directory with the `OpenCL` directory and 2. you have no authority to access these source files. The corresponding solutions are 1. put the `Vina-GPU` executable file under the `Vina-GPU` directory, in which you also have the `OpenCL` directory and 2. try `sudo ./Vina-GPU --config ./input_file_example/2bm2_config.txt`

We also recommend you to try our example first by typing `./Vina-GPU --config ./input_file_example/2bm2_config.txt`

If your problem is still unsolved, please feel free to contact us : )

**Comment by EmanuelD1989** [comment]
Hi, I faced the same issue. I tried the code ./Vina-GPU --config ./input_file_example/2bm2_config.txt from Vina-GPU folder, the result is satisfying. However, when I ran Vina-GPU from my project folder using full path, the same error was shown

Platform: NVIDIA CUDA
Build kernels from sourceError: failed to open file
: ./OpenCL/src/kernels/code_head.cppError: failed to open file
: ./OpenCL/src/kernels/mutate_conf.cppError: failed to open file
: ./OpenCL/src/kernels/matrix.cppError: failed to open file
: ./OpenCL/src/kernels/quasi_newton.cppError: failed to open file
Segmentation fault (core dumped)

**Comment by Glinttsd** [comment]
Hi, thanks for the feedback, as mentioned in the README, for the second time you run Vina-GPU, type `make` (instead of `make source`). The binary file `Vina-GPU` should be able to run in anywhere else (because it doesn't need the `OpenCL/` files anymore)
