### ISSUE TITLE
Paramters to support docking with macrocycles

### ISSUE THREAD

**Issue by JSLJ23** [DeltaGroupNJUPT/Vina-GPU#30]
Hi,

Just wondering if there were any other flags or special config arugments to better support docking compounds with macrocycles?
The failure rate for docking macrocycle compounds is pretty high ~14%.
Is there anything more than the default parameters that might help bring this docking failure rate down?

Thank you.

**Comment by Glinttsd** [comment]
Hi, sure, you can either try increasing `search_depth`  and `thread`, which will perform more optimization on searching the best comformation, or try to narrow down `size_x/y/z`, which will help decrease the difficulty of finding the best position. Hope them help.

**Comment by JSLJ23** [comment]
Ok I will give that a shot, thank you!
