### ISSUE TITLE
fl rmsd_upper_bound(): Assertion `a.size() == b.size()` failed

### ISSUE THREAD

**Issue by shazj99** [DeltaGroupNJUPT/Vina-GPU#33]
While doing large scale virtual screening using Vina-GPU, many molecules fail because of the assertion error:
```
CUDA_VISIBLE_DEVICES=1 ./Vina-GPU --receptor protein.pdbqt --ligand 1.pdbqt --num_modes 1 
--center_x 7.2395000000000005 --center_y -0.6745000000000001 --center_z 31.628500000000003
--size_x 9.583 --size_y 19.809 --size_z 12.779 --thread 10000 --out res.pdbqt: 

Vina-GPU: ./lib/coords:31 fl rmsd_upper_bound(const vecv&, const vecv&): Assertion `a.size() == b.size()` failed
```
@Glinttsd Do you have any idea of this?  Is there any configuration that can prevent it or does retry work?

Thanks in advance!

**Comment by Glinttsd** [comment]
Hi, this could be caused by any problem that interrupts the docking procudure performed on GPU. You can try to run the problem ligand manually and see if the program die immediately. Also, you can try to decease `thread` to see what will happend
