### ISSUE TITLE
Any parameters to reduce memory consumption in config.txt?

### ISSUE THREAD

**Issue by JSLJ23** [DeltaGroupNJUPT/Vina-GPU#34]
Hi,

I was wondering if there were any parameters that could be given to reduce the memory consumption of `Vina-GPU` during docking to avoid the `Err-6:CL_OUT_OF_HOST_MEMORY` as I have other concurrent processes running on my GPU and can only afford about 4GB for `Vina-GPU`...
Thank you.

**Comment by JonasLi-19** [comment]
I also encountered this kind of error, but` Err-5-OUT...`

How do you deal with it?

BTW, help me check if my config.txt right for receptor and ligand path setting:

```
receptor = 2019_refined_set/10gs/10gs_pocket.pdbqt
ligand = 2019_refined_set/10gs/10gs_ligand.pdbqt
out = 2019_refined_set/10gs/10gs_out.pdbqt
```

**Comment by JSLJ23** [comment]
I did not manage to resolve this, unfortunately.
