### ISSUE TITLE
Multiple Ligand Docking does not work

### ISSUE THREAD

**Issue by emacocucci** [DeltaGroupNJUPT/Vina-GPU#41]
Hi, 

In my hands multiple ligand dockign does not work. 
If I use the option you suggest:
--ligand_directory arg   ligand directory, if virtual screening is needed
  --output_directory arg   output directory, if virtual screening is needed
The software generates _out directory and does not save anything.

If I wrote a code in python or batch to dock, it runs but does not save. 
This is the batch code I use: 

@echo off

for %%F in (*.pdbqt) do (
    echo Processing file: %%F
    G:\MacrocycleScreening\Vina-GPU-2.0-main\Vina-GPU+\Vina-GPU+.exe ^
--ligand "%%F" --receptor G:\MacrocycleScreening\Molecule_For_Dock.pdbqt ^
--thread 8000 ^
--center_x -35 ^
--center_y 8 ^
--center_z 14 ^
--size_x 15 ^
--size_y 20 ^
--size_z 15
 )

If I run a dock at the time it works, so clearly is a problem of how it saves. 
Can you resolve this?

Thanks

**Comment by Glinttsd** [comment]
HI, multi ligand docking is enabled in Vina-GPU 2.0 (not Vina-GPU), you can try our newest version.
