### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Calder10** [DeltaGroupNJUPT/Vina-GPU#42]
I follow all the instructions given in Read me file.. but returns following error:

cc1plus: fatal error: ../boost_1_82_0/libs/thread/src/pthread/thread.cpp: No such file or directory
compilation terminated.
cc1plus: fatal error: ../boost_1_82_0/libs/thread/src/pthread/once.cpp: No such file or directory
compilation terminated.
make: *** [Makefile:21: source] Error 1

**Comment by Glinttsd** [comment]
Hi, please check your installation directory of the boost library. I think you have not installed it in the `../boost_1_82_0`, which causing these errors.
