### ISSUE TITLE
HOW to set the center to be 'as the ligand center'?

### ISSUE THREAD

**Issue by RJ-Li** [DeltaGroupNJUPT/Vina-GPU#45]
I need to dock multiple complexes, so I need to do this work to find some easy method to set the center as ligand center.

**Comment by RJ-Li** [comment]
plus, I have an important question to ask you: How did you process the numerous pdb files which have ions such as Zn in the dataset in to pdbqt? I find they cannot be converted into PDBQT files, but I DON'T wanna deal with them with AutoDockZn(this method might use different scoring function than vina scoring funtion, so I cannot categorize them into vina)

**Comment by Glinttsd** [comment]
Hi, you can read the pdbqt file line by line and record the xyz coordinates of each atom of the ligand. Then, you can calculate the center of the ligand by averaging all the coordinates.

Sorry I can help you with the second question. I guess AutoDock Vina can not deal with Zn atom, neither does Vina-GPU.
