### ISSUE TITLE
Error5 CL-OUT-OF-RESOURCES ?

### ISSUE THREAD

**Issue by JonasLi-19** [DeltaGroupNJUPT/Vina-GPU#46]
@Glinttsd  used the docker to do vina-gpu docking, in its workdir, it already contains Vina-GPU and other files you mentioned in README.

When I use it, the command is like:` ./Vina-GPU --config config.txt`

And the config.txt is like:
```
receptor = ./2019_refined_set_withPQT/187l/187l_pocket.pdbqt
ligand = ./2019_refined_set_withPQT/187l/187l_ligand.pdbqt
out = ./2019_refined_set_withPQT/187l/187l_out.pdbqt
center_x = 27.117375
center_y = 6.956125
center_z = 3.680125
size_x = 25
size_y = 25
size_z = 25
thread = 8000 
```

BUT there is something wrong reported about CL-OUT-OF-RESOURCES...
![image](https://github.com/DeltaGroupNJUPT/Vina-GPU/assets/54503824/a25401b7-6d75-455e-b5cc-68d473c40850)

**Comment by Glinttsd** [comment]
Hi, please check the avaliable cpu memory and gpu memory. Some other users may take up a large amount of memeory, so that you run into the CL_OUT_OF_RESOURCES error. You can also try `ulimit -s 8192`. Hope it works.
