### ISSUE TITLE
Precission is bad

### ISSUE THREAD

**Issue by EmanuelD1989** [DeltaGroupNJUPT/Vina-GPU#7]
I redocked the ligand from PDB 5 times, the binding energy value range was quite high for the best pose (from 7.4 - 9.2). It is quite bad when compared with regular vina since it gave narrow range of binding energy (from 9.1 - 9.3). Regular autodock vina clearly gave constant value and better value of RMSD.

**Comment by Glinttsd** [comment]
Hi, thanks for the feedback. Vina-GPU is able to change the most important two hyperparameters (thread & search_depth) manually, increasing them should improve the accuracy.
For more information about the accuracy, please check out our preprint paper in [https://chemrxiv.org/engage/chemrxiv/article-details/619b82a09960f3f750b7ad7c](url).
